// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-y0FJ_qzMl79-ylHUTbHwNxMJ9ii5uw',
    appId: '1:738251653132:web:0b98857bfbaac35fdfee29',
    messagingSenderId: '738251653132',
    projectId: 'quickstudy-9deb2',
    authDomain: 'quickstudy-9deb2.firebaseapp.com',
    storageBucket: 'quickstudy-9deb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZMKEO7wI61m1lL1V-5Jpx2GgPtjUydmI',
    appId: '1:738251653132:android:c214151dc88c7cd9dfee29',
    messagingSenderId: '738251653132',
    projectId: 'quickstudy-9deb2',
    storageBucket: 'quickstudy-9deb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0FGkd85ZGrKKSIjxrWRvwI3hiJUNRguM',
    appId: '1:738251653132:ios:6f8eee91d03318c3dfee29',
    messagingSenderId: '738251653132',
    projectId: 'quickstudy-9deb2',
    storageBucket: 'quickstudy-9deb2.firebasestorage.app',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0FGkd85ZGrKKSIjxrWRvwI3hiJUNRguM',
    appId: '1:738251653132:ios:6f8eee91d03318c3dfee29',
    messagingSenderId: '738251653132',
    projectId: 'quickstudy-9deb2',
    storageBucket: 'quickstudy-9deb2.firebasestorage.app',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3-y0FJ_qzMl79-ylHUTbHwNxMJ9ii5uw',
    appId: '1:738251653132:web:d212292c32957aabdfee29',
    messagingSenderId: '738251653132',
    projectId: 'quickstudy-9deb2',
    authDomain: 'quickstudy-9deb2.firebaseapp.com',
    storageBucket: 'quickstudy-9deb2.firebasestorage.app',
  );
}
